package main

import (
	"fmt"

	"github.com/WesEfird/GoLancer/sysinfo"
)

func main() {
	// DEMO read list of files generated by sysinfo.GetFileList
	fmt.Println(sysinfo.GetInfo())

	fileList := sysinfo.LoadFileList("files.txt")
	fmt.Println(fileList)
}
